name: Docker Compose CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and run Docker Compose
      - name: Build and Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d



      # Stop and remove the containers after the job
      - name: Stop and Remove Containers
        run: docker-compose -f docker-compose.yml down
